#!/usr/bin/env bash

echo "Number of occurences of be4e071c11594bb0b4ee3c444fd08b99in the input file:"

grep -o -i be4e071c11594bb0b4ee3c444fd08b99 data | wc -l

echo "Number of occurences of be4e071c11594bb0b4ee3c444fd08b99in the output file:"

grep -o -i be4e071c11594bb0b4ee3c444fd08b99 productB.csv | wc -l

echo "Distinct number of occurrences of the events in the output of ProductA:"

awk -F ',' '{print $3}' productA.csv | sort | uniq -c
